spring:
  application:
    name: E-Commerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #     validator:
    #       apply_to_ddl: true

  sql:
    init:
      mode: always

  jwt:
    secret_key: ${JWT_SECRET}
    issuer: E-Commerce
    audience: localhost
    accessTokenExpirationInSeconds: 7200 # 2 hours
    refreshTokenExpirationInSeconds: 604800 # 7 days


stripe:
  secretKey: ${STRIPE_SECRET_KEY}